### ISSUE TITLE
[FEATURE] List of Supervisors / Students who have Not Yet Met Submission Requirements

### ISSUE THREAD

**Issue by jhebus** [pkitazos/allocation-app#200]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a button that produces a list of the people (students / supervisors) who have not submitted there work leading up to a deadline so that a coordinator can press a button to get the list of relevant people and then copy the list to an email, and send an email reminder.

**Describe the solution you'd like**

A button that produces a list in the format that can be copy pasted into an email for:
- supervisors who have not met their target
- students who have not made their project selections

**Describe alternatives you've considered**

**Additional context**

**Comment by pkitazos** [comment]
I'll try to have this implemented before the update tomorrow, in the meantime, there is a partial solution to the problem. Here's what you can do:

1. press on `add filters` and select "Target Not Met"
<img width="1419" alt="Screenshot 2024-08-26 at 14 54 41" src="https://github.com/user-attachments/assets/2be6ba97-de5b-4288-8aa0-103b439ad8c0">

2. expand the table to show 50 rows
<img width="1419" alt="Screenshot 2024-08-26 at 14 59 03" src="https://github.com/user-attachments/assets/23d690f7-0d52-4b62-aa1a-ddb41eb682c1">

3. select all the rows using the checkbox in the header of the first column (this selects all rows in view, i.e. the first 50 since we expanded the table rows)
<img width="1419" alt="Screenshot 2024-08-26 at 14 54 51" src="https://github.com/user-attachments/assets/ae176133-5057-45de-97c7-1f61915571d2">

4. Once all/some rows are selected three dots should appear in the header of the last column, replacing the word "Actions". Click the three dots and select the option "Download selected rows" from the dropdown menu.
<img width="1419" alt="Screenshot 2024-08-26 at 14 55 09" src="https://github.com/user-attachments/assets/918b91ed-e82d-4f56-b49e-c18a6cb18348">

5. repeat for as many pages as necessary (in our case it should just be 2)

**Comment by jhebus** [comment]
Got it - thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
